export default constants = {
    'API_KEY': 'AIzaSyBXSuOnKD1jTWv6RsZVKK6qqBuevq1dNCU'
}

export const screens = {
    BOOKINGMODULE: "BOOKINGMODULE",
    USERLOCATION: "USERLOCATION",
    ADDRESSREFINEMENT: "ADDRESSREFINEMENT",
    AGENCYSELECTIONMODULE: "AGENCYSELECTIONMODULE"
}